### ISSUE TITLE
-f 옵션 누락

### ISSUE THREAD

**Issue by codelabor** [DaleSeo/DaleSeo.github.io#10]
* 위치: https://www.daleseo.com/docker-containers/
* 세부 위치: 컨테이너 로그 확인

* AS-IS: 
```console
-f 옵션을 사용하면 실시간 로그를 확인할 수 있습니다.
$ docker logs amazing_chatelet
```

* TO-BE;
```console
-f 옵션을 사용하면 실시간 로그를 확인할 수 있습니다.
$ docker logs -f amazing_chatelet
```

수정해서 pull request 드리려했으나 사내망에서 edit가 허용되지 않아 Issue로 올립니다.

**Comment by DaleSeo** [comment]
정정 하였습니다. 제보 감사드립니다!
